[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
recur = "Du86TLvDNSzGf1hkb6cVPoQpHPCwYiRXnGKm3J1GAgFj"

[programs.localnet]
recur = "Du86TLvDNSzGf1hkb6cVPoQpHPCwYiRXnGKm3J1GAgFj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
