export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  NONCE_NOT_FOUND: "NONCE_NOT_FOUND",
  NONCE_EXPIRED: "NONCE_EXPIRED",
  NONCE_ALREADY_USED: "NONCE_ALREADY_USED",
  NONCE_WALLET_MISMATCH: "NONCE_WALLET_MISMATCH",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_BASE58: "INVALID_BASE58",

  MERCHANT_NOT_FOUND: "MERCHANT_NOT_FOUND",
  APP_NOT_FOUND: "APP_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_INACTIVE: "PLAN_INACTIVE",
  SUBSCRIBER_NOT_FOUND: "SUBSCRIBER_NOT_FOUND",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",

  MISSING_APP_ID: "MISSING_APP_ID",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ERROR_HTTP_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,

  NONCE_NOT_FOUND: 400,
  NONCE_EXPIRED: 400,
  NONCE_ALREADY_USED: 400,
  NONCE_WALLET_MISMATCH: 400,
  INVALID_SIGNATURE: 401,
  INVALID_BASE58: 400,

  MERCHANT_NOT_FOUND: 404,
  APP_NOT_FOUND: 404,
  PLAN_NOT_FOUND: 404,
  PLAN_INACTIVE: 400,
  SUBSCRIBER_NOT_FOUND: 404,
  SUBSCRIPTION_NOT_FOUND: 404,

  MISSING_APP_ID: 400,
};

export interface ApiSuccess<T = unknown> {
  success: true;
  data: T;
  error: null;
}

export interface ApiFailure {
  success: false;
  data: null;
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
  };
}

export type ApiResult<T = unknown> = ApiSuccess<T> | ApiFailure;
